package com.caixin.transfer.entity.product;

import java.math.BigDecimal;
import java.util.Date;

public class BussProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.merchants_id
     *
     * @mbggenerated
     */
    private Integer merchantsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.cat_id
     *
     * @mbggenerated
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.main_pic
     *
     * @mbggenerated
     */
    private String mainPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.main_pic_first
     *
     * @mbggenerated
     */
    private String mainPicFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.other_pic
     *
     * @mbggenerated
     */
    private String otherPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.other_pic_first
     *
     * @mbggenerated
     */
    private String otherPicFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.webp_pic
     *
     * @mbggenerated
     */
    private String webpPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.webp_pic_first
     *
     * @mbggenerated
     */
    private String webpPicFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.is_virtual
     *
     * @mbggenerated
     */
    private String isVirtual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.start_sale_time
     *
     * @mbggenerated
     */
    private Date startSaleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.last_modify_user
     *
     * @mbggenerated
     */
    private Integer lastModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.is_receipt
     *
     * @mbggenerated
     */
    private String isReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.is_guarantee
     *
     * @mbggenerated
     */
    private String isGuarantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.buss_mould_id
     *
     * @mbggenerated
     */
    private Integer bussMouldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.union_postage
     *
     * @mbggenerated
     */
    private BigDecimal unionPostage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.max_price
     *
     * @mbggenerated
     */
    private BigDecimal maxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.min_price
     *
     * @mbggenerated
     */
    private BigDecimal minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.shop_id
     *
     * @mbggenerated
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.exp_date
     *
     * @mbggenerated
     */
    private Integer expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.exp_unit
     *
     * @mbggenerated
     */
    private String expUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.logistics_range
     *
     * @mbggenerated
     */
    private String logisticsRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.contraband_status
     *
     * @mbggenerated
     */
    private String contrabandStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.sale_count_his
     *
     * @mbggenerated
     */
    private Integer saleCountHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.commodity_score
     *
     * @mbggenerated
     */
    private BigDecimal commodityScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.sale_count
     *
     * @mbggenerated
     */
    private Integer saleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.zone
     *
     * @mbggenerated
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buss_product_info.region
     *
     * @mbggenerated
     */
    private String region;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.id
     *
     * @return the value of buss_product_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.id
     *
     * @param id the value for buss_product_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.merchants_id
     *
     * @return the value of buss_product_info.merchants_id
     *
     * @mbggenerated
     */
    public Integer getMerchantsId() {
        return merchantsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.merchants_id
     *
     * @param merchantsId the value for buss_product_info.merchants_id
     *
     * @mbggenerated
     */
    public void setMerchantsId(Integer merchantsId) {
        this.merchantsId = merchantsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.name
     *
     * @return the value of buss_product_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.name
     *
     * @param name the value for buss_product_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.cat_id
     *
     * @return the value of buss_product_info.cat_id
     *
     * @mbggenerated
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.cat_id
     *
     * @param catId the value for buss_product_info.cat_id
     *
     * @mbggenerated
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.main_pic
     *
     * @return the value of buss_product_info.main_pic
     *
     * @mbggenerated
     */
    public String getMainPic() {
        return mainPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.main_pic
     *
     * @param mainPic the value for buss_product_info.main_pic
     *
     * @mbggenerated
     */
    public void setMainPic(String mainPic) {
        this.mainPic = mainPic == null ? null : mainPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.main_pic_first
     *
     * @return the value of buss_product_info.main_pic_first
     *
     * @mbggenerated
     */
    public String getMainPicFirst() {
        return mainPicFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.main_pic_first
     *
     * @param mainPicFirst the value for buss_product_info.main_pic_first
     *
     * @mbggenerated
     */
    public void setMainPicFirst(String mainPicFirst) {
        this.mainPicFirst = mainPicFirst == null ? null : mainPicFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.other_pic
     *
     * @return the value of buss_product_info.other_pic
     *
     * @mbggenerated
     */
    public String getOtherPic() {
        return otherPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.other_pic
     *
     * @param otherPic the value for buss_product_info.other_pic
     *
     * @mbggenerated
     */
    public void setOtherPic(String otherPic) {
        this.otherPic = otherPic == null ? null : otherPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.other_pic_first
     *
     * @return the value of buss_product_info.other_pic_first
     *
     * @mbggenerated
     */
    public String getOtherPicFirst() {
        return otherPicFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.other_pic_first
     *
     * @param otherPicFirst the value for buss_product_info.other_pic_first
     *
     * @mbggenerated
     */
    public void setOtherPicFirst(String otherPicFirst) {
        this.otherPicFirst = otherPicFirst == null ? null : otherPicFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.webp_pic
     *
     * @return the value of buss_product_info.webp_pic
     *
     * @mbggenerated
     */
    public String getWebpPic() {
        return webpPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.webp_pic
     *
     * @param webpPic the value for buss_product_info.webp_pic
     *
     * @mbggenerated
     */
    public void setWebpPic(String webpPic) {
        this.webpPic = webpPic == null ? null : webpPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.webp_pic_first
     *
     * @return the value of buss_product_info.webp_pic_first
     *
     * @mbggenerated
     */
    public String getWebpPicFirst() {
        return webpPicFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.webp_pic_first
     *
     * @param webpPicFirst the value for buss_product_info.webp_pic_first
     *
     * @mbggenerated
     */
    public void setWebpPicFirst(String webpPicFirst) {
        this.webpPicFirst = webpPicFirst == null ? null : webpPicFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.is_virtual
     *
     * @return the value of buss_product_info.is_virtual
     *
     * @mbggenerated
     */
    public String getIsVirtual() {
        return isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.is_virtual
     *
     * @param isVirtual the value for buss_product_info.is_virtual
     *
     * @mbggenerated
     */
    public void setIsVirtual(String isVirtual) {
        this.isVirtual = isVirtual == null ? null : isVirtual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.status
     *
     * @return the value of buss_product_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.status
     *
     * @param status the value for buss_product_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.start_sale_time
     *
     * @return the value of buss_product_info.start_sale_time
     *
     * @mbggenerated
     */
    public Date getStartSaleTime() {
        return startSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.start_sale_time
     *
     * @param startSaleTime the value for buss_product_info.start_sale_time
     *
     * @mbggenerated
     */
    public void setStartSaleTime(Date startSaleTime) {
        this.startSaleTime = startSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.create_user
     *
     * @return the value of buss_product_info.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.create_user
     *
     * @param createUser the value for buss_product_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.create_time
     *
     * @return the value of buss_product_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.create_time
     *
     * @param createTime the value for buss_product_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.last_modify_user
     *
     * @return the value of buss_product_info.last_modify_user
     *
     * @mbggenerated
     */
    public Integer getLastModifyUser() {
        return lastModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.last_modify_user
     *
     * @param lastModifyUser the value for buss_product_info.last_modify_user
     *
     * @mbggenerated
     */
    public void setLastModifyUser(Integer lastModifyUser) {
        this.lastModifyUser = lastModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.last_modify_time
     *
     * @return the value of buss_product_info.last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.last_modify_time
     *
     * @param lastModifyTime the value for buss_product_info.last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.is_delete
     *
     * @return the value of buss_product_info.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.is_delete
     *
     * @param isDelete the value for buss_product_info.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.is_receipt
     *
     * @return the value of buss_product_info.is_receipt
     *
     * @mbggenerated
     */
    public String getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.is_receipt
     *
     * @param isReceipt the value for buss_product_info.is_receipt
     *
     * @mbggenerated
     */
    public void setIsReceipt(String isReceipt) {
        this.isReceipt = isReceipt == null ? null : isReceipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.is_guarantee
     *
     * @return the value of buss_product_info.is_guarantee
     *
     * @mbggenerated
     */
    public String getIsGuarantee() {
        return isGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.is_guarantee
     *
     * @param isGuarantee the value for buss_product_info.is_guarantee
     *
     * @mbggenerated
     */
    public void setIsGuarantee(String isGuarantee) {
        this.isGuarantee = isGuarantee == null ? null : isGuarantee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.buss_mould_id
     *
     * @return the value of buss_product_info.buss_mould_id
     *
     * @mbggenerated
     */
    public Integer getBussMouldId() {
        return bussMouldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.buss_mould_id
     *
     * @param bussMouldId the value for buss_product_info.buss_mould_id
     *
     * @mbggenerated
     */
    public void setBussMouldId(Integer bussMouldId) {
        this.bussMouldId = bussMouldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.union_postage
     *
     * @return the value of buss_product_info.union_postage
     *
     * @mbggenerated
     */
    public BigDecimal getUnionPostage() {
        return unionPostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.union_postage
     *
     * @param unionPostage the value for buss_product_info.union_postage
     *
     * @mbggenerated
     */
    public void setUnionPostage(BigDecimal unionPostage) {
        this.unionPostage = unionPostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.brand_id
     *
     * @return the value of buss_product_info.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.brand_id
     *
     * @param brandId the value for buss_product_info.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.max_price
     *
     * @return the value of buss_product_info.max_price
     *
     * @mbggenerated
     */
    public BigDecimal getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.max_price
     *
     * @param maxPrice the value for buss_product_info.max_price
     *
     * @mbggenerated
     */
    public void setMaxPrice(BigDecimal maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.min_price
     *
     * @return the value of buss_product_info.min_price
     *
     * @mbggenerated
     */
    public BigDecimal getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.min_price
     *
     * @param minPrice the value for buss_product_info.min_price
     *
     * @mbggenerated
     */
    public void setMinPrice(BigDecimal minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.shop_id
     *
     * @return the value of buss_product_info.shop_id
     *
     * @mbggenerated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.shop_id
     *
     * @param shopId the value for buss_product_info.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.exp_date
     *
     * @return the value of buss_product_info.exp_date
     *
     * @mbggenerated
     */
    public Integer getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.exp_date
     *
     * @param expDate the value for buss_product_info.exp_date
     *
     * @mbggenerated
     */
    public void setExpDate(Integer expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.exp_unit
     *
     * @return the value of buss_product_info.exp_unit
     *
     * @mbggenerated
     */
    public String getExpUnit() {
        return expUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.exp_unit
     *
     * @param expUnit the value for buss_product_info.exp_unit
     *
     * @mbggenerated
     */
    public void setExpUnit(String expUnit) {
        this.expUnit = expUnit == null ? null : expUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.logistics_range
     *
     * @return the value of buss_product_info.logistics_range
     *
     * @mbggenerated
     */
    public String getLogisticsRange() {
        return logisticsRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.logistics_range
     *
     * @param logisticsRange the value for buss_product_info.logistics_range
     *
     * @mbggenerated
     */
    public void setLogisticsRange(String logisticsRange) {
        this.logisticsRange = logisticsRange == null ? null : logisticsRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.contraband_status
     *
     * @return the value of buss_product_info.contraband_status
     *
     * @mbggenerated
     */
    public String getContrabandStatus() {
        return contrabandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.contraband_status
     *
     * @param contrabandStatus the value for buss_product_info.contraband_status
     *
     * @mbggenerated
     */
    public void setContrabandStatus(String contrabandStatus) {
        this.contrabandStatus = contrabandStatus == null ? null : contrabandStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.sale_count_his
     *
     * @return the value of buss_product_info.sale_count_his
     *
     * @mbggenerated
     */
    public Integer getSaleCountHis() {
        return saleCountHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.sale_count_his
     *
     * @param saleCountHis the value for buss_product_info.sale_count_his
     *
     * @mbggenerated
     */
    public void setSaleCountHis(Integer saleCountHis) {
        this.saleCountHis = saleCountHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.commodity_score
     *
     * @return the value of buss_product_info.commodity_score
     *
     * @mbggenerated
     */
    public BigDecimal getCommodityScore() {
        return commodityScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.commodity_score
     *
     * @param commodityScore the value for buss_product_info.commodity_score
     *
     * @mbggenerated
     */
    public void setCommodityScore(BigDecimal commodityScore) {
        this.commodityScore = commodityScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.summary
     *
     * @return the value of buss_product_info.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.summary
     *
     * @param summary the value for buss_product_info.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.sale_count
     *
     * @return the value of buss_product_info.sale_count
     *
     * @mbggenerated
     */
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.sale_count
     *
     * @param saleCount the value for buss_product_info.sale_count
     *
     * @mbggenerated
     */
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.province
     *
     * @return the value of buss_product_info.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.province
     *
     * @param province the value for buss_product_info.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.city
     *
     * @return the value of buss_product_info.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.city
     *
     * @param city the value for buss_product_info.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.zone
     *
     * @return the value of buss_product_info.zone
     *
     * @mbggenerated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.zone
     *
     * @param zone the value for buss_product_info.zone
     *
     * @mbggenerated
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buss_product_info.region
     *
     * @return the value of buss_product_info.region
     *
     * @mbggenerated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buss_product_info.region
     *
     * @param region the value for buss_product_info.region
     *
     * @mbggenerated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }
}