package com.caixin.transfer.mapper.product;

import com.caixin.transfer.entity.product.BussProductInfo;

public interface BussProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_product_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_product_info
     *
     * @mbggenerated
     */
    int insert(BussProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_product_info
     *
     * @mbggenerated
     */
    int insertSelective(BussProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_product_info
     *
     * @mbggenerated
     */
    BussProductInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_product_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BussProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buss_product_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BussProductInfo record);
}